version: "3.9"
services:
    mysql:
        image: mysql:8
        volumes:
            - ./docker/mysql-data/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'itguys'
            MYSQL_DATABASE: 'itguys'
        ports:
            - "3306:3306"

    webserver:
        image: nginx:alpine
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - php-fpm

    php-fpm:
        build: docker/php-fpm
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        depends_on:
            - mysql

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
