dateModified: 1611992873
email:
  fromEmail: $EMAIL_SYSTEM_ADDRESS
  fromName: $EMAIL_SENDER_NAME
  replyToEmail: $EMAIL_SYSTEM_ADDRESS
  template: null
  transportSettings:
    encryptionMethod: tls
    host: $EMAIL_HOST
    password: $EMAIL_PASSWORD
    port: $EMAIL_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $EMAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
system:
  edition: solo
  live: true
  name: itguys.ro
  retryDuration: null
  schemaVersion: 3.6.1
  timeZone: Europe/Bucharest
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
