name: Deploy

on:
  push:
    branches: [ "master","main" ]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      CRAFT_ALLOW_SUPERUSER: 1
    steps:
      - run: cd /var/www/itguys.ro && ./deploy.sh
